DROP TABLE IF EXISTS blog;
DROP TABLE IF EXISTS users;

CREATE TABLE users(
      id SERIAL PRIMARY KEY,
      first_name VARCHAR(255) NOT NULL,
      last_name VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL UNIQUE,
      password VARCHAR(255) NOT NULL,
      admin BOOLEAN NOT NULL DEFAULT FALSE,
      editor BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE blog(
      id SERIAL PRIMARY KEY,
      title TEXT NOT NULL,
      post TEXT NOT NULL,
      user_id INTEGER NOT NULL REFERENCES users(id),
      publish BOOLEAN NOT NULL DEFAULT FALSE,
      image VARCHAR,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
